#!/bin/bash

mkdir -p /tmp/parsepkgbuild

source /etc/makepkg.conf
export CARCH

PARSE_PKGBUILD_PATH=${PARSE_PKGBUILD_PATH:-/usr/share/namcap}

exec </dev/null
exec /usr/bin/env -i PATH=/dummy /bin/bash --norc --noprofile -r "$PARSE_PKGBUILD_PATH"/parsepkgbuild.sh $1
